name: Trigger auto deployment for ethinix-admin-app-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ethinix-admin-app-prod-AutoDeployTrigger-792e6e0f-9946-44ce-b204-dd5c92d1b7d0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ETHINIXADMINAPPPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ETHINIXADMINAPPPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ETHINIXADMINAPPPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name ethnixapps

      - name: Check Permissions
        run: az containerapp show -g ReactAPPS -n ethinix-admin-app-prod --query identity

      - name: Get Container Environment Variables
        id: get-env-vars
        run: |
          # Instalar jq para procesar JSON
          sudo apt-get update && sudo apt-get install -y jq
          
          # Obtener las variables de entorno del contenedor
          ENV_VARS=$(az containerapp show \
            --name ethnix-admin-app-qa \
            --resource-group ReactAPPS \
            --query 'properties.template.containers[0].env' \
            --output json)
          
          echo "Variables de entorno obtenidas:"
          echo $ENV_VARS | jq '.'
          
          # Convertir a formato de argumentos de build Docker
          BUILD_ARGS=""
          if [ "$ENV_VARS" != "null" ] && [ ! -z "$ENV_VARS" ]; then
            BUILD_ARGS=$(echo $ENV_VARS | jq -r '.[] | select(.name != null and .value != null) | "--build-arg \(.name)=\(.value)"' | tr '\n' ' ')
          fi
          
          # Si no hay variables, usar valor por defecto
          if [ -z "$BUILD_ARGS" ]; then
            BUILD_ARGS=""
          fi
          
          echo "Build arguments: $BUILD_ARGS"
          echo "build_args=$BUILD_ARGS" >> $GITHUB_OUTPUT

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePathKey_
          _targetLabelKey_: _targetLabel_
          registryUrl: ethnixapps.azurecr.io
          registryUsername: ${{ secrets.ETHINIXADMINAPPPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ETHINIXADMINAPPPROD_REGISTRY_PASSWORD }}
          containerAppName: ethinix-admin-app-prod
          resourceGroup: ReactAPPS
          imageToBuild: ethnixapps.azurecr.io/ethinix-admin-app-prod:${{ github.sha }}
          buildArgumentsKey: ${{ steps.get-env-vars.outputs.build_args }}




