name: Trigger auto deployment for ethnix-admin-test

on:
  push:
    branches: [QA]
    paths:
    - '**'
    - '.github/workflows/ethnix-admin-test-AutoDeployTrigger-71cfe4c7-0f45-40c7-b9c1-69c15bb549eb.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ETHNIXADMINTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ETHNIXADMINTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ETHNIXADMINTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          containerAppName: ethnix-admin-test
          resourceGroup: ReactAPPS
          # Azure automáticamente detectará y usará el registry configurado
          # y aplicará la etiqueta correcta automáticamente
