name: Trigger auto deployment for ethnix-admin-app-qa

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ QA ]
    paths:
    - '**'
    - '.github/workflows/ethnix-admin-app-qa-AutoDeployTrigger-73e861ba-7f11-4455-8100-38221e4099c8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ETHNIXADMINAPPQA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ETHNIXADMINAPPQA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ETHNIXADMINAPPQA_AZURE_SUBSCRIPTION_ID }}

      - name: Obtener variables de entorno desde Azure Container App
        run: |
          export NEXT_PUBLIC_BASE_URL=$(az containerapp show --name ethnix-admin-app-qa --resource-group ReactAPPS --query "properties.template.containers[0].env[?name=='NEXT_PUBLIC_BASE_URL'].value" -o tsv)
          echo "NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL" >> $GITHUB_ENV
          export NEXTAUTH_URL=$(az containerapp show --name ethnix-admin-app-qa --resource-group ReactAPPS --query "properties.template.containers[0].env[?name=='NEXTAUTH_URL'].value" -o tsv)
          echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> $GITHUB_ENV
          export NEXTAUTH_SECRET=$(az containerapp show --name ethnix-admin-app-qa --resource-group ReactAPPS --query "properties.template.containers[0].env[?name=='NEXTAUTH_SECRET'].value" -o tsv)
          echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> $GITHUB_ENV

          # Validación y defaults para build
          if [ -z "$NEXT_PUBLIC_BASE_URL" ]; then
            echo "NEXT_PUBLIC_BASE_URL no definido en Azure, usando valor por defecto"
            NEXT_PUBLIC_BASE_URL="http://localhost:3000"
          fi
          
          if [ -z "$NEXTAUTH_URL" ]; then
            echo "NEXTAUTH_URL no definido en Azure, usando valor por defecto"
            NEXTAUTH_URL="http://localhost:3000"
          fi
          
          if [ -z "$NEXTAUTH_SECRET" ]; then
            echo "NEXTAUTH_SECRET no definido en Azure, usando valor por defecto"
            NEXTAUTH_SECRET="temporarysecret"
          fi
          
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ethnixadminqa.azurecr.io
          registryUsername: ${{ secrets.ETHNIXADMINAPPQA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ETHNIXADMINAPPQA_REGISTRY_PASSWORD }}
          containerAppName: ethnix-admin-app-qa
          resourceGroup: ReactAPPS
          imageToBuild: ethnixadminqa.azurecr.io/ethnix-admin-app-qa:${{ github.sha }}
          _buildArgumentsKey_: |
             NEXT_PUBLIC_BASE_URL=${{ env.NEXT_PUBLIC_BASE_URL }}
             NEXTAUTH_URL=${{ env.NEXTAUTH_URL }}
             NEXTAUTH_SECRET=${{ env.NEXTAUTH_SECRET }}







