name: Trigger auto deployment for ethnix-admin-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ QA ]
    paths:
    - '**'
    - '.github/workflows/ethnix-admin-test-AutoDeployTrigger-da920b3a-76f4-4a04-885e-66dbce413ec6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ETHNIXADMINTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ETHNIXADMINTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ETHNIXADMINTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2.2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.ETHNIXADMINTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ETHNIXADMINTEST_REGISTRY_PASSWORD }}
          containerAppName: ethnix-admin-test
          resourceGroup: ReactAPPS
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_




