name: Trigger auto deployment for ethnix-admin-app-qa

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ fix/caotic_container ]
    paths:
    - '**'
    - '.github/workflows/ethnix-admin-app-qa-AutoDeployTrigger-c78e3e98-5891-4800-bb8f-f9cdcbf4b5ad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ETHNIXADMINAPPQA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ETHNIXADMINAPPQA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ETHNIXADMINAPPQA_AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name ethnixadminqa

      - name: Check Permissions
        run: az containerapp show -g ReactAPPS -n ethnix-admin-app-qa --query identity

      - name: Obtener variables de Azure Container App
        run: |
          echo "NEXT_PUBLIC_BASE_URL=$(az containerapp show -g ReactAPPS -n ethnix-admin-app-qa --query "properties.template.containers[0].envVars[?name=='NEXT_PUBLIC_BASE_URL'].value" -o tsv)" >> $GITHUB_ENV
          echo "NEXTAUTH_URL=$(az containerapp show -g ReactAPPS -n ethnix-admin-app-qa --query "properties.template.containers[0].envVars[?name=='NEXTAUTH_URL'].value" -o tsv)" >> $GITHUB_ENV
          echo "NEXTAUTH_SECRET=$(az containerapp show -g ReactAPPS -n ethnix-admin-app-qa --query "properties.template.containers[0].envVars[?name=='NEXTAUTH_SECRET'].value" -o tsv)" >> $GITHUB_ENV
        
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ethnixadminqa.azurecr.io
          registryUsername: ${{ secrets.ETHNIXADMINAPPQA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ETHNIXADMINAPPQA_REGISTRY_PASSWORD }}
          containerAppName: ethnix-admin-app-qa
          resourceGroup: ReactAPPS
          imageToBuild: ethnixadminqa.azurecr.io/ethnix-admin-app-qa:${{ github.sha }}
          _buildArgumentsKey_: |
             NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
             NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
             NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            
      



















